# Deploy to Cloud Run
# Usage: gcloud builds submit --config=cloudbuild.yaml
#        --substitutions=_INSTANCE_CONNECTION_NAME=proj:region:inst,_DB_USER=appuser,_DB_NAME=appdb,_DB_PASS=yourpass

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: user-management-app

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},DB_PASS=${_DB_PASS}'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
